### ISSUE TITLE
zgcommunities nicht hochgeladen u:rise recipe

### ISSUE THREAD

**Issue by Fionarin** [Wunderbyte-GmbH/Moodle-tool_wbinstaller#12]
{
          "shortname": "zgcommunities",
          "name": "{mlang de}Zielgruppe auswählen für Landing Pages & Filter \"Interessant für\"{mlang}{mlang en}Select target group for landing pages & “Interesting for” filter{mlang}",
          "type": "dynamicformat",
          "data": {
            "required": "0",
            "uniquevalues": "0",
            "dynamicsql": "SELECT *\\r\\nFROM (SELECT 'Wissenschaftliches Personal' AS id, '{mlang de}Wissenschaftliches Personal{mlang}{mlang en}Academic staff{mlang}' AS data, 1 as sortorder\\r\\nUNION\\r\\nSELECT 'PhD Students' AS id, 'PhD Students' AS data, 2 as sortorder\\r\\nUNION\\r\\nSELECT 'PostDoc' AS id, 'PostDoc' AS data, 3 as sortorder\\r\\nUNION\\r\\nSELECT 'Allgemeines Personal' AS id, '{mlang de}Allgemeines Personal{mlang}{mlang en}General staff{mlang}' AS data, 4 as sortorder\\r\\nUNION\\r\\nSELECT 'Führungskräfte' AS id, '{mlang de}Führungskräfte{mlang}{mlang en}Executive staff{mlang}' AS data, 5 as sortorder\\r\\nUNION\\r\\nSELECT 'Studierende' AS id, '{mlang de}Studierende{mlang}{mlang en}Students{mlang}' AS data, 6 as sortorder\\r\\nUNION\\r\\nSELECT 'Interessierte Öffentlichkeit' AS id, '{mlang de}Interessierte Öffentlichkeit{mlang}{mlang en}General public{mlang}' AS data, 6 as sortorder) as s1\\r\\norder by sortorder ASC",
            "autocomplete": "1",
            "defaultvalue": "",
            "multiselect": "1",
            "locked": "0",
            "visibility": "2"
          }
        }

**Comment by WunderJacob** [comment]
dynamicformat bitte zu dynamic ändern
