### ISSUE TITLE
Nach dem Upload des Rezepts keine Reaktion

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/Moodle-tool_wbinstaller#13]
Hi,

ich komme beim Testen des Installers nicht weiter. Nachdem ich das alise-Rezept
[alise_recipe.zip](https://github.com/user-attachments/files/17431662/alise_recipe.zip)

geladen habe...
![grafik](https://github.com/user-attachments/assets/2fddcaf9-a335-4092-b2cc-cf9876838723)

zeigt es mir eine quasi leere, funktionslose Seite an:
![grafik](https://github.com/user-attachments/assets/bf43f948-8db1-4bc9-a82c-66929b7b1c22)

Auch bein Klick auf Install startet nichts.

Mache ich etwas falsch oder habe ich ein korruptes Rezept am Start?

**Comment by WunderJacob** [comment]
Servus Ralf, ich kümmere mich darum.

**Comment by WunderJacob** [comment]
@ralferlebach 
Okay, ich habe es mir mal angeschaut. Das Rezept funktioniert soweit. Könntest du des Plugin bitte deinstallieren und nochmals installieren und auch den Github Token eingeben (damit werden die Plugins gechecked? Du solltest bei dem Rezept zumindest die Checks sehen. Des blaue "Installieren" ist auch eher ein Tab und kein Button. Im Foto siehst du wie der install button aussieht.
Zur Not machen wir einen kurzen Call. 
![Bildschirmfoto 2024-10-21 um 08 20 18](https://github.com/user-attachments/assets/6ff24a17-f33d-45f6-a0cb-7a7d08229b32)

**Comment by ralferlebach** [comment]
Habe ich gemacht, leider keine Änderung am Zustand: Ich sehe keinen Install-Button und auch keinen Check.
![grafik](https://github.com/user-attachments/assets/2c9eb494-e598-48c2-bceb-465312fe1022)

**Comment by WunderJacob** [comment]
Github-Token ist nur notwendig wenn du Plugins installierst. Die Daten der Plugins bekommst du über die github-api und die lässt dich ohne token nur bestimmt viele Aufrufe machen. Können wir kurz einen call machen, dann kann ich mir den Fehler auf deinem System genau mal anschauen

**Comment by ralferlebach** [comment]
OK.

Zoom-Raum:
https://uni-wuppertal.zoom.us/j/96734291527?pwd=TnNvOVhWaTdKejRZRHBYUElKbXJOZz09
 
Meeting-ID: 967 3429 1527
Passwort: xS5DqRbS

**Comment by WunderJacob** [comment]
[urise_recipe.zip](https://github.com/user-attachments/files/17505601/urise_recipe.zip)

**Comment by ralferlebach** [comment]
{
  "error": [
    "Der Base64-String ist nicht gültig."
  ]
}

**Comment by WunderJacob** [comment]
@ralferlebach könntest du mit der neusten version von dem installer 2024102400 und diesem Rezept hier schauen was für eine Fehlermeldung jetzt ausgespuckt wird? 
Ich kann leider den Fehler nicht reproduzieren bei mir.
[learningpath_recipe.zip](https://github.com/user-attachments/files/17507782/learningpath_recipe.zip)

**Comment by WunderJacob** [comment]
@ralferlebach 
können wir uns heute des Verhalten nochmal anschauen? 
Ich habe eine neue Version hochgeladen. Vielleicht klappt es ja jetzt auf deiner Maschine.

**Comment by ralferlebach** [comment]
Leider noch keine Besserung der Situation... so langsam mache ich mir Sorgen über meine eigenen Fähigkeiten.

**Comment by ralferlebach** [comment]
... und noch der Zoom-Raum.

https://uni-wuppertal.zoom.us/j/96734291527?pwd=TnNvOVhWaTdKejRZRHBYUElKbXJOZz09

**Comment by ralferlebach** [comment]
Hat sich nun gelöst, dafür gibt es jetzt #15, #16 und #17
