### ISSUE TITLE
ERROR: Schreibrechtprobleme, obwohl voller Schreibzugriff gewährt ist

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/Moodle-tool_wbinstaller#15]
Beim Ausführen von:
[alise_recipe.zip](https://github.com/user-attachments/files/17574499/alise_recipe.zip)

![grafik](https://github.com/user-attachments/assets/b2278e39-b71b-4616-9ab1-714d7bf54497)

Alle Verzeichnisse wurden jedoch mittel chmod -R 777 ./ global für alle Nutzer schreibzugriffsberechtigt gemacht.

Die nachfolgende systemgetriggerte Installation scheitert dann an dem fehlenden adaptivequizcatmodel_catquiz (2024062800) - Plugin.

![grafik](https://github.com/user-attachments/assets/e29664ba-40e0-4787-9fe9-38899597db6d)

**Comment by WunderJacob** [comment]
Fehler wird geworfen weil der Ordner noch nicht existiert. das subplugin wird ja in den catquiz Ordner reingeschrieben.

**Comment by ralferlebach** [comment]
Das Problem ist nach wie vor nicht zur Zufriedenheit gelöst.

![grafik](https://github.com/user-attachments/assets/de08d072-b9d1-4f11-8416-c36f20d80431)

Das mod_adaptive ist offenbar nicht installiert, damit erklärt sich technisch der angezeigte Fehler. Für den Nutzer ist dies jedoch nicht erkennbar, dass es sich hierbei um einen Hinweis und nicht um einen Fehler handelt.

In Fällen wie diesen, sollte wie besprochen in gelber Farbe angezeigt werden: "Hinweis: Verzeichnis xyz kann möglicherweise nicht angelegt werden. Dies kann u.a. durch fehlender Schreibrechte oder dadurch bedingt sein, dass der übergeordnete Ordner (noch) nicht existiert. Das Plugin wird im nächsten Schritt dennoch versuchen, die Komponente zu installieren."

Besser wäre natürlich, zu prüfen, ob der übergeordnete Ordner existiert und wenn dieser exisitert, welche Rechte dieser besitzt ( is_dir(), is_writeable() ).

Nach Schritt 1 (Installation der Plugins) ist alles ordnungsgemäß im Filesystem angelegt.
![grafik](https://github.com/user-attachments/assets/7d4b15da-2d48-4152-ad25-5843c8f34895)

Dennoch sind die Plugins offensichtlich allesamt NICHT installiert, Moodle triggert unter Webseiten-Adminstration -> Systemnachrichten nämlich sofort den Installationsprozess.
![grafik](https://github.com/user-attachments/assets/950e604f-b41c-487f-92e3-f1dba1251744)

Vorschlag:
Bevor hier zum Schritt 2 übergegangen wird, wäre es möglicherweise eine einfache und dennoch nutzerfreundliche Lösung, anstelle des "Nächster Schritt"-Buttons einen Button anzubieten, der "<root-dir>/admin/index.php" in einem neuen Tab öffnet und den Installationsprozess abarbeitet.

**Comment by ralferlebach** [comment]
Nachtrag:

Das Plugin behauptet zwar, die Plugins seien "erfolgreich installiert", ...

![grafik](https://github.com/user-attachments/assets/b3131b08-507a-4af4-9afc-eee96305d776)

... was sich allerdings bei einem Blick in die Datenbank als unwahre Tatsachenbehauptung darstellt:

![grafik](https://github.com/user-attachments/assets/c94a47c5-5c02-40e0-a63b-f9cd282ac037)

(Erkennbar daran, dass z.B. keinerlei Datenbanktabellen für mod_adaptive vorhanden sind.)
