### ISSUE TITLE
ERROR: Zugriff auf (noch?) nicht vorhandene Datenbank-Tabellen

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/Moodle-tool_wbinstaller#16]
Bei der Installation von

[learningpath_recipe.zip](https://github.com/user-attachments/files/17574602/learningpath_recipe.zip)

kommt es zu folgendem Fehler:

![grafik](https://github.com/user-attachments/assets/f039c060-6940-4c65-99aa-422ef5423ba3)

Offenbar wird versucht, bereits auf die Datenbanktabellen vom Lernpfad-Plugin zuzugreifen, bevor dieses installiert ist.

**Comment by WunderJacob** [comment]
Hier läuft der check ob das local plugin von adele installiert ist. Wie soll die Rückmeldung sonst aussehen?

**Comment by WunderJacob** [comment]
Bitte das neue Rezept für die Lernpfade verwenden. Es wird jetzt als Warnung ausgegeben mit entsprechendem Text
