### ISSUE TITLE
ERROR: CATQuiz-Einstellungen nach Installation offenbar nicht korrekt.

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/Moodle-tool_wbinstaller#17]
Nach manueller Installation des Adapters aus xxx das Rezept erneut ausgeführt.

Hier konnte die erste (Prüfungsseite) erfolgreich angezeigt werden, aber die Abarbeitung wurde als nicht erfolgreicher Abbruch angegeben.

Im CAT-Quiz des Kurses stehen nun merkwürdige Dinge in den Feedbacks:
![grafik](https://github.com/user-attachments/assets/02a52921-af33-416b-83ea-ef943acdc32e)

und falls Kurs- oder Gruppeneinschreibungen vorgenommen werden sollten: Das werden sie nicht.
![grafik](https://github.com/user-attachments/assets/e6b8e1e8-6353-416f-a764-7b7a5e51f25f)

**Comment by WunderJacob** [comment]
Was genau ist hier der Fehler?

**Comment by WunderJacob** [comment]
Hier werden lediglich die eingetragenen Werte ausgegeben.

**Comment by ralferlebach** [comment]
OK, dann ist das Rezept offenbar so gestaltet, dass die Ausgabe so aussieht, als wäre da irgendwas kaputt.

Um die Funktionalitäten des Installters mit ALiSe-Inhalten zu testen, wird ein Rezept benötigt, dass
- [ ] einen Kurs mit drei Gruppen "ALiSe_A01", "ALiSe_A02" und "ALiSe_A03" anlegt
- [ ] drei Kurse mit den Namen "Rot 1", "Grün 1" und "Rot 2" anlegt. Diese Kurse beinhalten einen Link (mod_url), der auf den o.g. Kurs verweisen.
- [ ] im Kurs mit den Gruppen "ALiSe_A01", "ALiSe_A02" und "ALiSe_A03" einem ALiSe-Test anlegt, der
- [ ] das unterste Defizit der ersten 3 Skalen der Skala "Simulation", also Sim-A01, Sim-A02 und Sim-A03 bestimmt
- [ ] die geschieht in den zwei Bereichen (rot und grün), wobei der Wechsel von Rot zu Grün für A01 bei -3, A02 bei -2 und A03 bei -1 geschehen soll
- [ ] für die Skalen A01, A02 und A03 die schriftlichen Feedbacks den Text "Feedback für den Bereich <ROT/GRÜN> von Skala <SKALENNAME>" beinhaltet. Bei Skala A01 soll zudem ein Link auf den Kurs "Rot 1" bzw. "Grün 1", bei Skala A03 soll zudem jeweils ein Bild im Text enthalten sein.
- [ ] die Skalen Simulation sowie Sim-A sollen vom Reporting ausgenommen sein
- [ ] für Skala A01 sowie A02 (rot) soll eine Einschreibung in den jeweiligen Kurs vorgenommen werden
- [ ] für Skala A01, A02 und A03 soll im Fall von "grünen Ergebnissen" der TN in die Gruppe" ALiSe_A01", "ALiSe_A02" und "ALiSe_A03" eingeschrieben werden.

Das Arrangement habe ich in der Form bereits auf alise.wunderbyte.at vorbereitet.
https://alise.wunderbyte.at/course/index.php?categoryid=11

**Comment by ralferlebach** [comment]
Das neue Rezept funktioniert nicht.

Unter Linux unter Windows entsteht ein Wheel of Death nach dem Hochladen des Rezeptes, und MAMP auf Mac gibt es sofort eine (nicht näher definierte) Fehlermeldung mit Abbruch.

Beim Öffnen der ZIP-Datei habe ich im Dateinamen folgendes vorgefunden:
![grafik](https://github.com/user-attachments/assets/54172f1b-18b9-4410-8c2d-74a67526aed6)

Könnte das die Ursache des Problems sein?

**Comment by ralferlebach** [comment]
Nach einem Blick in die error.log scheint vielmehr dies hier die Ursache (zumindest im WSL-Setup) zu sein:

[Tue Nov 12 10:56:43.864906 2024] [php:notice] [pid 567] [client ::1:36784] PHP Warning:  PHP Request Startup: POST Content-Length of 14873238 bytes exceeds the limit of 8388608 bytes in Unknown on line 0, referer: http://localhost/moodle01/admin/tool/wbinstaller/index.php/
[Tue Nov 12 10:56:44.052048 2024] [core:notice] [pid 249] AH00052: child pid 567 exit signal Segmentation fault (11)

Wird hier eine Voraussetzung in der php.ini verlangt, die zu den Voraussetzungen von Moodle gehört und die aufgrund verletzt und nicht abgefangen wird?
