### ISSUE TITLE
Fehlermeldung, wenn Upload größer als erlaubt

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/Moodle-tool_wbinstaller#21]
Nach Ändern der Standard-Einstellung post_max_size = 8M zu 128M ist das Problem mit dem Nicht-Starten eines größeren Rezeptes behoben. Daher bitte, wie im Standard-Upload von Moodle, eine aussagekraftige Fehlermeldung ausgeben und den Nutzer auf die Ursache des Problems hinweisen. Danke

https://github.com/Wunderbyte-GmbH/Moodle-tool_wbinstaller/issues/17#issuecomment-2470362554

              Nach einem Blick in die error.log scheint vielmehr dies hier die Ursache (zumindest im WSL-Setup) zu sein:

             [Tue Nov 12 10:56:43.864906 2024] [php:notice] [pid 567] [client ::1:36784] PHP Warning:  PHP Request Startup: POST Content-Length of 14873238 bytes exceeds the limit of 8388608 bytes in Unknown on line 0, referer: http://localhost/moodle01/admin/tool/wbinstaller/index.php/
             [Tue Nov 12 10:56:44.052048 2024] [core:notice] [pid 249] AH00052: child pid 567 exit signal Segmentation fault (11)

             Unter MAMP findet man im nginx-error.log:
             2024/11/12 11:24:45 [error] 4794#0: *343 client intended to send too large body: 14873225 bytes, client: 127.0.0.1, server: , request: "POST /moodle01/lib/ajax/service.php?sesskey=HGxdDdLzGh&info=tool_wbinstaller_check_recipe HTTP/1.1", host: "localhost:8888", referrer: "http://localhost:8888/moodle01/admin/tool/wbinstaller/index.php/"

             Wird hier eine Voraussetzung in der php.ini verlangt, die zu den Voraussetzungen von Moodle gehört und die aufgrund verletzt und nicht abgefangen wird?

_Originally posted by @ralferlebach in https://github.com/Wunderbyte-GmbH/Moodle-tool_wbinstaller/issues/17#issuecomment-2470362554_

**Comment by WunderJacob** [comment]
@ralferlebach Servus Ralf, wir haben jetzt nochmals separat abgefangen ob die plugins auch wirklich installiert sind. Gib einfach kurz Bescheid ob und wie es läuft

**Comment by ralferlebach** [comment]
Aktuelle "Fehlermeldung": "Request Entity Too Large"
![grafik](https://github.com/user-attachments/assets/c3129e72-6562-4823-9e8e-9aee9c7c81d1)

Interessanterweise liefern auch Core-Funktionen von Moodle (z.B. der Filepicker) aktuell keine vernünftigen Fehler zurück, daher lassen wir das jetzt erst einmal so.
