### ISSUE TITLE
ERROR: Linkauflösung in mod_url schlägt (noch) fehlt

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/Moodle-tool_wbinstaller#29]
Die Verlinkungen in den Feedback-Texten scheinen nun zu funktionieren:
![grafik](https://github.com/user-attachments/assets/f990688b-fbeb-41e3-9aad-6339c55daaa2)

Verlinkungen in mod_url zwischen den importierten Kursen werden noch nicht aufgelöst:
![grafik](https://github.com/user-attachments/assets/34fd806c-6b4c-421f-be69-495972a4228d)

**Comment by WunderJacob** [comment]
Merci für die Info. Ich schau mir des heute gleich an.

**Comment by WunderJacob** [comment]
Bitte checken

**Comment by ralferlebach** [comment]
Perkekt
