### ISSUE TITLE
Create receipt for complete Alise Project

### ISSUE THREAD

**Issue by georgmaisser** [Wunderbyte-GmbH/Moodle-tool_wbinstaller#3]
- [ ] Install all plugins
- [ ] Install courses and question DB
- [ ] Install scale structure & item params via csv
- [ ] Fix courseids in new installation

**Comment by davidszkiba** [comment]
@WunderJacob 

Plugin dependencies:

- wunderbyte_table: https://github.com/Wunderbyte-GmbH/moodle-local_wunderbyte_table
- mod_adaptivequiz (noch unser fork): https://github.com/Wunderbyte-GmbH/moodle-mod_adaptivequiz/tree/wb-0.9.0-rc2
- adaptivequiz caquiz catmodel: https://github.com/Wunderbyte-GmbH/moodle-adaptivequizcatmodel_catquiz/tree/1.0.2 Das muss in `mod/adaptivequiz/catmodel/catquiz` installiert werden
- local_catquiz: https://github.com/Wunderbyte-GmbH/moodle-local_catquiz/tree/1.0.3
- shortcodes: https://github.com/branchup/moodle-filter_shortcodes
