### ISSUE TITLE
Nachträglicher Zugriff auf Plugin-Einstellungen ermöglichen (gab es schon einmal, ist wieder verschwunden)

### ISSUE THREAD

**Issue by ralferlebach** [Wunderbyte-GmbH/Moodle-tool_wbinstaller#33]
## Userstory ##
Als Administrator möchte ich auch nachträglich die Plugin-Eigenschaften einsehen oder ändern können, damit ich z.B. den GH-Token erneuern oder herauskopieren kann.

## Anforderungen (objektiv & testbar) ##
- [ ] "Einstellungen" in der Plugin-Übersicht anbieten
![grafik](https://github.com/user-attachments/assets/a66c4114-9b50-4381-ae0b-851329dd77ff)

## Definition of Done ##
- [ ] Alle Anforderungen sind erfüllt
- [ ] Alle Anforderungen erfolgreich getestet
- [ ] Der Code ist übersichtlich strukturiert und mit Kommentaren versehen
- [ ] Nicht gebrauchte Code-Passagen sind entfernt
- [ ] Offene Punkte & Bugs in Tickets dokumentiert

**Comment by WunderJacob** [comment]
_"Einstellungen" in der Plugin-Übersicht anbieten_ -> Bitte über den vorgesehen Weg die Einstellungen ändern
![Bildschirmfoto 2024-12-04 um 10 44 44](https://github.com/user-attachments/assets/9c33de7f-cada-420f-9209-351cb9472f5d)

**Comment by georgmaisser** [comment]
Vielleicht kann ich hier noch anfügen:
Es gibt hier eine Diskussion dazu. In Local Plugins ist das aktuell unseres Wissens nach nicht möglich:
https://moodle.org/mod/forum/discuss.php?d=426266

**Comment by ralferlebach** [comment]
OK.
